# Generated by Django 4.2.4 on 2023-08-29 21:06

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to=projects.models.proyect_pic_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('recomended', models.BooleanField(default=False)),
            ],
        ),
    ]
