# Generated by Django 4.2.4 on 2023-08-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='recomended',
            field=models.BooleanField(default=False),
        ),
    ]
